import '@digdir/designsystemet-css/index.css';
import 'rk-design-tokens/design-tokens-build/theme.css';
import 'rk-designsystem/dist/rk-designsystem.css';
import { Source_Sans_3 } from 'next/font/google';
import './globals.css';

const sourceSans3 = Source_Sans_3({
  subsets: ['latin'],
  weight: ['200','300','400','500','600','700','800','900'],
  style: ['normal','italic'],
});

export const metadata = {
  title: "Nye rodekors.no",
  description: 'Generated by Figma MCP Compiler',
};

export default function RootLayout({ children }) {
  return (
    <html lang="no">
      <body className={sourceSans3.className}>{children}</body>
    </html>
  );
}
